# Generated by Django 6.0.6 on 2026-06-25 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único seguro para o arquivo', unique=True)),
                ('mime_type', models.CharField(help_text='Tipo do arquivo (png, jpg, pdf ou txt)', max_length=100)),
                ('tamanho', models.BigIntegerField(help_text='Tamanho do arquivo em bytes')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
