# Generated by Django 6.0.6 on 2026-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_arquivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
